name: Workflow Validation

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions: {}

jobs:
  actionlint:
    name: Actionlint
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Lint workflows
        uses: docker://rhysd/actionlint@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667 #  version 1.7.12
        with:
          args: -color
